name = "cloudflare-test1"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-01-01"

[vars]
VITE_DL_DETAIL_FETCH_LIMIT = "2"
VITE_DL_MAX_CONCURRENCY = "6"
VITE_EMBEDDING_MODEL = "google/text-embedding-004"
VITE_INFERENCE_MODEL = "google/gemini-1.5-flash-latest"
# secret - VITE_BEARER_TOKEN = "---secret---"
# secret - VITE_BRAVE_SUBSCRIPTION_TOKEN = "---secret---"
# secret - VITE_GEMINI_API_KEY = "---secret---"
# secret - VITE_DEMO_TOKEN = "---secret---"
